// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hand-garden-styles/InkAndBloom.tsx": () => import("../components/mockups/hand-garden-styles/InkAndBloom.tsx"),
  "./components/mockups/hand-garden-styles/LuminousNight.tsx": () => import("../components/mockups/hand-garden-styles/LuminousNight.tsx")
};
